# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jarvis_march_cpp <- function(points) {
    .Call(`_jarvismarch_jarvis_march_cpp`, points)
}

